version: '3'

services:
  ui-prod:
    build:
      context: ./ui
      dockerfile: app-ui.prod.Dockerfile
    image: balavigneswaran/exp-ui:2.5
    ports:
      - 80:80
    stdin_open: true
    # depends_on:
    #   - mongodb-app
  api:
    build:
      context: ./api
      dockerfile: app-api.prod.Dockerfile
    image: balavigneswaran/exp-api:2.5
    environment:
      # - MONGO_URL=mongodb://mongodb-app:27017
      - MONGO_URL=mongodb://host.docker.internal:27017
      - DB_NAME=expense
      - LOG_PATH=/logs
      - PORT=8000
    volumes:
      - 'C:/Java/logs:/logs'
    ports:
      - 8000:8000
    # networks:
    #   - expensenet
    # depends_on:
    #   - mongodb-app
  # mongodb-app:
  #   build:
  #     context: .
  #     dockerfile: app-db.Dockerfile
  #   image: expense-db-2
  #   volumes:
  #     - 'mongodata:/data/db'
  #   ports:
  #     - 27017:27017
  #   expose:
  #     - '27017'
  #   networks:
  #     - expensenet
# networks:
#   expensenet:
# volumes:
#   mongodata:
