version: '3'

services:
  ui-dev:
    build:
      context: ./ui
      dockerfile: app-ui.dev.Dockerfile
    image: expense-ui-dev
    environment:
      - PORT=3000
    volumes:
      - './ui:/app'
    ports:
      - 3001:3000
    stdin_open: true
    depends_on:
      - mongodb-app
  api-dev:
    build:
      context: ./api
      dockerfile: app-api.dev.Dockerfile
    image: expense-api-dev
    command: nodemon --exec npm run babel-node src/bin/server.js --region=dev | bunyan
    environment:
      - MONGO_URL=mongodb://mongodb-app:27017
      - DB_NAME=expense-test
      - LOG_PATH=/logs
      - PORT=8000
    volumes:
      - 'C:/Java/logs:/logs'
      - './api:/app'
    ports:
      - 8000:8000
    networks:
      - expensetestnet
    depends_on:
      - mongodb-app
  mongodb-app:
    build:
      context: .
      dockerfile: app-db.Dockerfile
    image: expense-db-dev
    volumes:
      - 'mongotestdata:/data/db'
    ports:
      - 27017:27017
    expose:
      - '27017'
    networks:
      - expensetestnet
  # this is commented out, just to disable.
  # mongo-express:
  #   image: mongo-express
  #   links:
  #     - mongodb:mongo
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - expensenet

networks:
  expensetestnet:

volumes:
  mongotestdata:
