export const BILLS_TAB = { UNPAID: 'UNPAID', PAID: 'PAID', OPEN: 'OPEN' };
export const ENTRY_TAB = { EXPENSE: 'EXPENSE', ADJUSTMENT: 'ADJUSTMENT' };
export const PAGINATION_BLOCK = { BILLS: 'BILLS', EXPENSES: 'EXPENSES', ACCOUNTS: 'ACCOUNTS' };
export const EXPENSE_BLOCK = { DASHBOARD: 'DASHBOARD', SEARCH: 'SEARCH' };
