root: true
parser: "@babel/eslint-parser"
extends:
  - react-app
env:
  es6: true
  node: true
  browser: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
  plugins:
    - 'react'
  extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'
    - 'plugin:prettier/recommended'
    - 'google'
