root: true
env:
  es6: true
  node: true
  mongo: true
  mocha: true
extends:
  - 'eslint:recommended'
  # - "plugin:@typescript-eslint/eslint-recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
# parser: "@typescript-eslint/parser"
parser: esprima
parserOptions:
  ecmaVersion: 2018
  sourceType: module
# plugins:
#   - "@typescript-eslint"
